#ifndef MICROKIT_CONFIG_LOGGER_H
#define MICROKIT_CONFIG_LOGGER_H

#include "microkit/lib/types.h"

#define MICROKIT_CONFIG_LOGGER_USE_COLORS 1
#define MICROKIT_CONFIG_LOGGER_USE_SOURCE_LINES 0
#define MICROKIT_CONFIG_LOGGER_USE_TIMESTAMPS TRUE

#endif
